# Info
author:
  name: Rowan Weismiller
  email: rowan.weismiller@gmail.com
  twitter: rowbot_weisguy
  github: rowbot-weisguy
  avatar_url: /assets/images/april-2016.jpg
  bio: Designer, developer, &amp; nacho critic

# Build
markdown: kramdown
kramdown:
    smart_quotes: ["rdquo", "rsquo", "ldquo", "rdquo"]
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
source: _src
destination: _public
permalink: /blog/:title/